export interface TimelineSelectionEventDetail {
  date: [string, string];
  instances: {
    // this is inaccurate, the type should include all possible sources and layers,
    layer: import("ol/layer/Layer").default;
    source: import("ol/source/Source").default;
  };
  filters: Record<string, any>;
  selectedItems: {
    [layerId: string]: SelectedItem[];
  };
}
export interface SelectedItem {
  className: string;
  date: string;
  group: string;
  // unique UUID for this item, generated by the timeline component
  id: string;
  itemId: string;
  local: string;
  originalDate: string;
  property: string;
  start: string;
  type: string;
  utc: string;
}

export interface TimelineExportEventDetail {
  eoxMapConfig: {
    layers: Record<string, any>[];
    zoom: number;
    center: [number, number];
  };
  filters: Record<string, any>;
  instances: {
    layer: import("ol/layer/Layer").default;
    source: import("ol/source/Source").default;
  };
  selectedRangeItems: {
    [layerId: string]: SelectedItem[];
  };
  generate: (args: {
    mapLayers: Array<{ layers: Record<string, any>[]; date: string }>;
    center?: [number, number];
    zoom?: number;
  }) => Promise<void>;
}
