export const CATEGORY_MAP = {
  EodashMap: "Visualization & Map",
  EodashLayerControl: "Visualization & Map",
  EodashItemCatalog: "Catalog & Discovery",
  EodashItemFilter: "Filtering & Selection",
  EodashTimeSlider: "Temporal Navigation",
  EodashDatePicker: "Temporal Navigation",
  EodashProcess: "Analysis & Processing",
  EodashChart: "Analysis & Processing",
  EodashStacInfo: "Branding & Metadata",
  EodashTools: "Layout & Orchestration",
  EodashLayoutSwitcher: "Layout & Orchestration",
};

export const TAGS_MAP = {
  EodashMap: [
    "map",
    "visualization",
    "layers",
    "openlayers",
    "geo",
    "spatial",
    "globe",
    "projection",
  ],
  EodashLayerControl: [
    "layer",
    "layers",
    "control",
    "visibility",
    "opacity",
    "visualization",
    "legend",
  ],
  EodashItemCatalog: [
    "catalog",
    "stac",
    "items",
    "discovery",
    "search",
    "filter",
    "collection",
  ],
  EodashItemFilter: [
    "filter",
    "filtering",
    "selection",
    "tag",
    "theme",
    "attribute",
    "search",
  ],
  EodashTimeSlider: [
    "time",
    "temporal",
    "slider",
    "datetime",
    "navigation",
    "animation",
    "range",
  ],
  EodashDatePicker: [
    "time",
    "temporal",
    "date",
    "picker",
    "datetime",
    "calendar",
  ],
  EodashProcess: [
    "process",
    "processing",
    "analysis",
    "jsonform",
    "service",
    "execution",
    "wps",
    "algorithms",
  ],
  EodashChart: [
    "chart",
    "vega",
    "graph",
    "timeseries",
    "statistics",
    "analysis",
    "plot",
  ],
  EodashStacInfo: [
    "info",
    "stac",
    "metadata",
    "citation",
    "branding",
    "details",
  ],
  EodashTools: ["tools", "layout", "toolbar", "actions", "orchestration"],
  EodashLayoutSwitcher: [
    "layout",
    "template",
    "switcher",
    "view",
    "orchestration",
  ],
};

export const STAC_EXTENSIONS_MAP = {
  EodashMap: [
    "eox:flatstyle",
    "eodash:rasterform",
    "proj:epsg",
    "eodash:mapProjection",
    "eodash:proj4_def",
    "eodash:merge_assets",
    "eodash:layerExclusive",
  ],
  EodashLayerControl: [
    "eox:flatstyle",
    "eodash:rasterform",
    "eodash:merge_assets",
    "eodash:layerExclusive",
  ],
  EodashItemCatalog: ["eo:cloud_cover"],
  EodashItemFilter: [],
  EodashTimeSlider: [],
  EodashDatePicker: [],
  EodashProcess: ["eodash:jsonform"],
  EodashChart: ["eodash:vegadefinition"],
  EodashStacInfo: ["sci:citation", "sci:doi", "sci:publication"],
};

export const STAC_CORE_FIELDS_MAP = {
  EodashMap: [],
  EodashLayerControl: [],
  EodashItemCatalog: ["datetime", "assets.thumbnail"],
  EodashItemFilter: ["themes", "tags", "summaries"],
  EodashTimeSlider: ["extent.temporal", "datetime"],
  EodashDatePicker: ["extent.temporal", "datetime"],
  EodashProcess: ["links (rel=service)"],
  EodashChart: ["links (rel=service, type=application/json|text/csv)"],
  EodashStacInfo: ["providers", "description", "title"],
};
