# .github/workflows/deploy_docs.yml
name: Deploy docs for main branch
on:
  push:
    branches:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: |
          npm install
          npm run docs:build -- --base /${{ github.event.repository.name }}/
      - uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          folder: ./docs/.vitepress/dist/
          branch: gh-pages
