name: Create dev release

on:
  pull_request:

permissions:
  contents: write

jobs:
  dev-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Set up NPM 🔧
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
      - name: Install dependencies 🔧
        run: npm ci
      - name: Detect which package changed ⚙️
        id: changed
        run: node core/node/scripts/changedPackages.js ${{ github.event.pull_request.base.sha }}
      - name: Build and publish package 🚀
        if: steps.changed.outputs.paths != ''
        run: npx pkg-pr-new publish --comment=update ${{ steps.changed.outputs.paths }}
