name: Create dev release

on:
  pull_request:

permissions:
  contents: write

jobs:
  dev-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up NPM 🔧
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
      - name: Install dependencies 🔧
        run: npm install
      - name: Build and publish package 🚀
        run: |
          npx pkg-pr-new publish --comment=update
