name: Create dev release

on:
  pull_request:

permissions:
  contents: write

jobs:
  dev-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Set up NPM 🔧
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
      - name: Install dependencies 🔧
        run: npm ci
      - name: Detect which package changed ⚙️
        id: changed
        run: node core/node/scripts/changedPackages.js ${{ github.event.pull_request.base.sha }}
      - name: Build and publish package 🚀
        if: steps.changed.outputs.paths != ''
        run: npx pkg-pr-new publish --comment=update ${{ steps.changed.outputs.paths }}
